import { CodexAdapter } from '../server/codex';
import { OpenCodeAdapter } from '../server/opencode';
import { writeFile } from 'node:fs/promises';
const codex=new CodexAdapter(process.env.CODEX_SOCKET||'/home/lujunxi57/.codex/app-server-control/app-server-control.sock');
const opencode=new OpenCodeAdapter();
const c=await codex.create('SessionWeave test · Codex B',true);
await writeFile('/tmp/sessionweave-test-codex.txt',c.id);
console.log('Codex test thread',c.id,c.model,c.effort);
const result=await codex.send(c.id,'这是 SessionWeave 的接入验证。不要使用工具，不修改文件。请只回答 SESSIONWEAVE_CODEX_OK。',[],[],a=>console.log(a.state,a.text,a.nativeId||''));
console.log('Codex result',JSON.stringify(result));
const o=await opencode.create('SessionWeave test · OpenCode loop A',true);
await writeFile('/tmp/sessionweave-loop-opencode.txt',o.id);
const r=await opencode.send(o.id,'这是接入验证，不要使用任何工具。只回答 SESSIONWEAVE_OPENCODE_SDK_OK。',[],[],a=>console.log(a.state,a.text));
console.log('OpenCode result',JSON.stringify(r));
codex.rpc.close();process.exit(0);
