import { useEffect, useMemo, useRef, useState } from 'react';
import { ReactFlow, ReactFlowProvider, Background, Controls, Handle, Position, MarkerType, useReactFlow, type Node, type NodeProps, type Connection, type NodeChange } from '@xyflow/react';
import { ArrowRight, Check, CheckCircle2, ChevronRight, Clock3, FileText, GitBranch, GripVertical, Layers3, LoaderCircle, Pause, Play, Plus, RefreshCw, Search, Sparkles, Terminal, Trash2, X } from 'lucide-react';
import type { Conversation, NodeRun, Resource, Step, Workflow, WorkflowRun } from '../shared/types';
import { api } from './api';
import Composer from './Composer';
import ModelPicker from './ModelPicker';
import { usePanelResize } from './PanelResize';
import EmployeeLayer, { usePixelPreferences } from './scene/EmployeeLayer';
import Station from './scene/Station';
import { stationState } from './scene/sceneState';
type StepData={step:Step;conversation?:Conversation;run?:NodeRun;selected:boolean;pixelEnabled:boolean;motion:boolean;entranceAt?:number};
type FlowNode=Node<StepData,'step'>;
const labels:Record<string,string>={idle:'空闲',unloaded:'历史会话',unavailable:'未连接',queued:'排队',running:'运行中',listening:'监听中',polishing:'润色中',approval:'待审批',succeeded:'已完成',failed:'失败',paused:'已暂停'};
const key=(c:{harness:string;id:string})=>`${c.harness}:${c.id}`;
const uid=()=>crypto.randomUUID();
const fresh=():Workflow=>({id:uid(),name:'未命名流程',nodes:[],edges:[]});
const relative=(time:number)=>{const m=Math.max(0,Math.floor((Date.now()-time)/60000));return m<1?'刚刚':m<60?`${m} 分钟前`:m<1440?`${Math.floor(m/60)} 小时前`:`${Math.floor(m/1440)} 天前`;};
function StepCard({data}:NodeProps<FlowNode>) {
  const {step,conversation:c,run:r,selected}=data;
  return <div className={`step-card ${selected?'selected':''} ${r?.state||''}`}>
    <Handle type="target" position={Position.Left}/><Handle type="source" position={Position.Right}/>
    <div className="step-top"><span className={`harness ${step.conversationRef.harness}`}>{step.conversationRef.harness==='codex'?'CX':'OC'}</span><span className="step-id">{step.id}</span><GripVertical size={15}/></div>
    <h3>{step.purpose}</h3><div className="node-conversation"><Terminal size={12}/>{c?.title||step.conversationRef.id.slice(0,16)}</div>
    <p className="prompt-preview">{step.mode==='listen'?'监听原客户端当前轮次，完成后接力。':step.promptTemplate||'点击节点，写下任务指令'}</p>
    <div className="node-refs">{step.selectedSkills.length>0&&<span>{step.selectedSkills.length} Skill</span>}{step.upstreamOutputRefs.map(id=><span key={id}>{id}.output</span>)}</div>
    {data.pixelEnabled&&<Station state={stationState(r)} entranceAt={data.entranceAt} motion={data.motion}/>}
    <div className="node-footer"><span className={`status-dot ${r?.state||''}`}/>{r?labels[r.state]:step.mode==='listen'?'监听当前轮':'等待运行'}<span className="node-model" title={`${r?.model||c?.model||'沿用会话配置'} · ${r?.effort||c?.effort||'默认'}`}>{r?.model||c?.model||'沿用会话配置'} · {r?.effort||c?.effort||'默认'}</span></div>
  </div>;
}
const nodeTypes={step:StepCard};
function Workbench() {
  const flow=useReactFlow();
  const panels=usePanelResize();
  const pixels=usePixelPreferences();
  const [ready,setReady]=useState(false),[entrances,setEntrances]=useState<Record<string,number>>({});
  const deploy=(ids:string[])=>setEntrances(Object.fromEntries(ids.map((id,i)=>[id,Date.now()+Math.min(i*70,280)])));
  const modelPickerOpen=useRef<(()=>void)|null>(null);
  const [creating,setCreating]=useState(false),[newHarness,setNewHarness]=useState<'codex'|'opencode'>('opencode'),[newTitle,setNewTitle]=useState('');
  const [sessions,setSessions]=useState<Conversation[]>([]),[connections,setConnections]=useState<Record<string,any>>({});
  const [workflow,setWorkflow]=useState<Workflow>(fresh),[selected,setSelected]=useState<string>(),[runs,setRuns]=useState<WorkflowRun[]>([]),[runId,setRunId]=useState<string>();
  const [dimensions,setDimensions]=useState<Record<string,{width:number;height:number}>>({});
  const [query,setQuery]=useState(''),[days,setDays]=useState('7'),[global,setGlobal]=useState(false),[harnessFilter,setHarnessFilter]=useState('all');
  const [chosen,setChosen]=useState<string[]>([]),[description,setDescription]=useState(''),[draft,setDraft]=useState<Workflow|null>(null);
  const [resources,setResources]=useState<Record<string,{skills:Resource[];commands:Resource[]}>>({}),[planSkills,setPlanSkills]=useState<Record<string,string[]>>({});
  const [historyTexts,setHistoryTexts]=useState<string[]>([]),[fileQuery,setFileQuery]=useState(''),[fileResults,setFileResults]=useState<string[]>([]);
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false),[planning,setPlanning]=useState(false),[starting,setStarting]=useState(false),[showRun,setShowRun]=useState(false),[mobilePanel,setMobilePanel]=useState<'sessions'|'plan'|null>(null);
  const activeRun=runs.find(r=>r.state==='running'||r.state==='paused');const run=runs.find(r=>r.id===runId)||runs[0];
  const step=workflow.nodes.find(n=>n.id===selected);const c=step&&sessions.find(c=>key(c)===key(step.conversationRef));
  const nodeRun=run?.workflow.id===workflow.id?run.nodes.find(n=>n.nodeId===selected):undefined;
  async function refresh() {setLoading(true);try{const d=await api('/api/sessions?refresh=true');setSessions(d.data);setConnections(d.connections);}catch(e){setError(String(e));}finally{setLoading(false);}}
  const protect=async(task:()=>Promise<void>)=>{setError('');try{await task();}catch(e){setError(e instanceof Error?e.message:String(e));}};
  useEffect(()=>{void refresh();void Promise.all([api<Workflow|null>('/api/workflow'),api<WorkflowRun[]>('/api/runs')]).then(([w,r])=>{if(w)setWorkflow(w);setRuns(r);setRunId(r.find(run=>run.workflow.id===w?.id)?.id||r[0]?.id);setReady(true);}).catch(e=>{setError(String(e));setReady(true);});
    const events=new EventSource('/api/events');let eventRevision=0;
    events.addEventListener('run',e=>{eventRevision++;const r=JSON.parse(e.data) as WorkflowRun;setRuns(old=>[r,...old.filter(x=>x.id!==r.id)]);});
    events.addEventListener('open',()=>{const revision=eventRevision;void api<WorkflowRun[]>('/api/runs').then(current=>{if(revision===eventRevision)setRuns(current);}).catch(()=>{});});
    const timer=setInterval(()=>{void api('/api/sessions').then(d=>{setSessions(d.data);setConnections(d.connections);}).catch(()=>{});},15000);
    return()=>{events.close();clearInterval(timer);};},[]);
  useEffect(()=>{if(!c)return;let valid=true;setHistoryTexts([]);void api('/api/history',{harness:c.harness,id:c.id}).then(h=>{if(valid)setHistoryTexts(h.map((m:any)=>m.text));}).catch(()=>{});
    if(!resources[key(c)])void api('/api/resources',{harness:c.harness,id:c.id}).then(r=>{if(valid)setResources(old=>({...old,[key(c)]:r}));}).catch(e=>setError(String(e)));
    return()=>{valid=false;};},[c?.id]);
  const visible=sessions.filter(c=>(harnessFilter==='all'||c.harness===harnessFilter)&&(global||days==='all'||Date.now()-c.updatedAt<Number(days)*86400000)&&`${c.title} ${c.preview}`.toLowerCase().includes(query.toLowerCase()));
  const nodes:FlowNode[]=workflow.nodes.map(n=>({id:n.id,type:'step',position:n.position,measured:dimensions[n.id],data:{step:n,conversation:sessions.find(c=>key(c)===key(n.conversationRef)),run:run?.workflow.id===workflow.id?run.nodes.find(r=>r.nodeId===n.id):undefined,selected:n.id===selected,pixelEnabled:pixels.enabled,motion:pixels.motion,entranceAt:entrances[n.id]}}));
  const edges=workflow.edges.map(e=>({...e,markerEnd:{type:MarkerType.ArrowClosed,color:'var(--accent)'},style:{stroke:'var(--accent)',strokeWidth:2},animated:!!activeRun&&pixels.motion}));
  const upstream=useMemo(()=>{const found=new Set<string>();function walk(id:string){for(const e of workflow.edges.filter(e=>e.target===id))if(!found.has(e.source)){found.add(e.source);walk(e.source);}}if(step)walk(step.id);return [...found];},[workflow.edges,step?.id]);
  function patchStep(changes:Partial<Step>){if(!step||activeRun)return;setWorkflow(w=>({...w,nodes:w.nodes.map(n=>n.id===step.id?{...n,...changes}:n)}));}
  async function toggleChosen(c:Conversation){const k=key(c);setChosen(old=>old.includes(k)?old.filter(x=>x!==k):[...old,k]);if(!resources[k])await protect(async()=>{const r=await api('/api/resources',{harness:c.harness,id:c.id});setResources(old=>({...old,[k]:r}));});}
  function add(c:Conversation,position?:{x:number;y:number}){if(activeRun)return;const id=`S${Date.now().toString(36)}`;const node:Step={id,conversationRef:{harness:c.harness,id:c.id},purpose:'新的任务步骤',mode:'kickoff',promptTemplate:'',selectedSkills:[],selectedFiles:[],upstreamOutputRefs:[],polishBeforeSend:false,position:position||{x:80+workflow.nodes.length*340,y:130}};setWorkflow(w=>({...w,nodes:[...w.nodes,node]}));setSelected(id);deploy([id]);}
  function connect(connection:Connection){if(activeRun||!connection.source||!connection.target||connection.source===connection.target)return;const e={id:uid(),source:connection.source,target:connection.target};setWorkflow(w=>({...w,edges:[...w.edges,e]}));}
  function changes(changes:NodeChange<FlowNode>[]){
    const measurements=changes.filter(x=>x.type==='dimensions');
    if(measurements.length)setDimensions(old=>{let next=old;for(const change of measurements)if(change.type==='dimensions'&&change.dimensions&&(old[change.id]?.width!==change.dimensions.width||old[change.id]?.height!==change.dimensions.height))next={...next,[change.id]:change.dimensions};return next;});
    if(activeRun||!changes.some(x=>x.type==='position'&&x.position))return;
    setWorkflow(w=>({...w,nodes:w.nodes.map(n=>{const p=changes.find(x=>x.type==='position'&&x.id===n.id);return p?.type==='position'&&p.position?{...n,position:p.position}:n;})}));
  }
  async function loop(){const picks=sessions.filter(c=>chosen.includes(key(c)));const a=picks.find(c=>c.harness==='opencode')||picks[0],b=picks.find(c=>c.harness==='codex')||picks[1];if(!a||!b||key(a)===key(b)){setError('先勾选两个不同会话，再创建 A → B → A');return;}
    const prompts=['阅读用户的研究主题，给出三个清晰的初步结论。','阅读上游结果，以 reviewer 角度提出批判意见。','根据 reviewer 意见完善最初结论，给出最终版本。'];const ids=['A1','B','A3'];deploy(ids);
    setWorkflow({id:uid(),name:'研究与评审 · A → B → A',nodes:ids.map((id,i)=>({id,conversationRef:{harness:(i===1?b:a).harness,id:(i===1?b:a).id},purpose:['初步研究','批判评审','修订收尾'][i],mode:'kickoff',promptTemplate:prompts[i],selectedSkills:[],selectedFiles:[],upstreamOutputRefs:i?[ids[i-1]]:[],polishBeforeSend:i>0,position:{x:80+i*350,y:160}})),edges:[{id:'a-b',source:'A1',target:'B'},{id:'b-a',source:'B',target:'A3'}]});setSelected('A1');setTimeout(()=>flow.fitView({padding:.15}),100);setNotice('三步画布已生成。编辑主题后点击运行。');}
  async function start(){setStarting(true);await protect(async()=>{await api('/api/workflow',workflow);const r=await api<WorkflowRun>('/api/runs',workflow);setRuns(old=>[r,...old]);setRunId(r.id);setShowRun(true);});setStarting(false);}
  async function save(){await protect(async()=>{await api('/api/workflow',workflow);setNotice('流程已保存到服务器');});}
  async function generate(){setPlanning(true);await protect(async()=>{const result=await api<Workflow>('/api/plan',{description,conversationKeys:chosen,selectedSkills:planSkills,previous:draft||workflow.nodes.length&&workflow||undefined});setDraft(result);setNotice('文字草稿已生成，确认后才改变画布。');});setPlanning(false);}
  function confirm(){if(!draft)return;deploy(draft.nodes.map(n=>n.id));setWorkflow(draft);setSelected(draft.nodes[0]?.id);setDraft(null);setMobilePanel(null);setTimeout(()=>flow.fitView({padding:.15}),100);setNotice('计划已确认。画布可继续编辑，点击运行才发送任务。');}
  function remove(){if(!step)return;setWorkflow(w=>({...w,nodes:w.nodes.filter(n=>n.id!==step.id).map(n=>({...n,upstreamOutputRefs:n.upstreamOutputRefs.filter(r=>r!==step.id)})),edges:w.edges.filter(e=>e.source!==step.id&&e.target!==step.id)}));setSelected(undefined);}
  async function findFiles(){await protect(async()=>{const d=await api('/api/files',{...step!.conversationRef,query:fileQuery});setFileResults(Array.isArray(d)?d:d.data||[]);});}
  return <div className="app-shell">
    <header className="app-header"><div className="brand"><span className="brand-mark"><GitBranch size={20}/></span><div>Session<span>Weave</span><small>让会话协作，让思路成形</small></div><span className="demo-label">DEMO</span></div>
      <div className="connection-pills">{['opencode','codex'].map(h=><span title={connections[h]?.error} key={h}><i className={connections[h]?.ok?'connected':''}/>{h==='codex'?'Codex':'OpenCode'}{connections[h]&&!connections[h].ok?' · 未连接':''}</span>)}</div><div className="header-end"><span className="local-label">LOCAL WORKSPACE</span><button className="icon-button mobile-toggle" aria-label="会话列表" onClick={()=>setMobilePanel(mobilePanel==='sessions'?null:'sessions')}><Layers3 size={18}/></button><button className="icon-button mobile-toggle" aria-label="计划面板" onClick={()=>setMobilePanel(mobilePanel==='plan'?null:'plan')}><Sparkles size={18}/></button></div></header>
    {error&&<div role="alert" className="banner error"><span>{error}</span><button aria-label="关闭错误" onClick={()=>setError('')}><X size={15}/></button></div>}{notice&&<div className="banner notice"><Check size={15}/><span>{notice}</span><button aria-label="关闭提示" onClick={()=>setNotice('')}><X size={15}/></button></div>}
    <main className="workspace" ref={panels.workspace} style={panels.style}>
      <aside className={`sessions-panel ${mobilePanel==='sessions'?'mobile-open':''}`}><div className="panel-title"><div><span className="eyebrow">01 / CONVERSATIONS</span><h2>会话资源 <span>{sessions.length}</span></h2></div><button className="icon-button" onClick={refresh} aria-label="刷新会话"><RefreshCw size={16} className={loading?'spin':''}/></button></div>
        <label className="search-field"><Search size={15}/><input placeholder="搜索标题与预览" aria-label="搜索会话" value={query} onChange={e=>setQuery(e.target.value)}/></label>
        <div className="filter-row"><select aria-label="时间范围" value={days} onChange={e=>setDays(e.target.value)}><option value="1">最近 24 小时</option><option value="7">最近 7 天</option><option value="30">最近 30 天</option><option value="all">全部时间</option></select><select aria-label="Harness 筛选" value={harnessFilter} onChange={e=>setHarnessFilter(e.target.value)}><option value="all">全部 Harness</option><option value="opencode">OpenCode</option><option value="codex">Codex</option></select></div>
        <label className="check-row muted"><input type="checkbox" checked={global} onChange={e=>setGlobal(e.target.checked)}/>全局搜索（忽略时间范围）</label><div className="list-caption">{visible.length} 个会话<span>拖入画布 · 勾选参与规划</span></div>
        <div className="session-list">{loading&&!sessions.length?<div className="empty-list"><LoaderCircle className="spin"/>正在读取真实会话…</div>:visible.length?visible.map(c=><article draggable={!activeRun} onDragStart={e=>{e.dataTransfer.setData('application/sessionweave',key(c));e.dataTransfer.effectAllowed='copy';}} className={`session-item ${chosen.includes(key(c))?'chosen':''}`} key={key(c)}>
          <div className="session-top"><label title="用于自然语言规划"><input aria-label={`选择 ${c.title}`} type="checkbox" checked={chosen.includes(key(c))} onChange={()=>void toggleChosen(c)}/></label><span className={`harness ${c.harness}`}>{c.harness==='codex'?'CX':'OC'}</span><strong>{c.title}</strong><button className="icon-button add-session" disabled={!!activeRun} aria-label={`添加步骤 ${c.title}`} onClick={()=>add(c)}><Plus size={15}/></button></div><p>{c.preview||'还没有聊天预览'}</p><div className="session-meta"><span><i className={`status-dot ${c.state}`}/>{labels[c.state]}</span><time>{relative(c.updatedAt)}</time></div></article>):<div className="empty-list"><Search size={25}/>没有匹配的会话<span>调整筛选范围或刷新连接</span></div>}</div>
        <div className="new-session"><select aria-label="新会话 Harness" disabled={creating||!!activeRun} value={newHarness} onChange={e=>setNewHarness(e.target.value as 'codex'|'opencode')}><option value="opencode">OpenCode</option><option value="codex">Codex</option></select><input aria-label="新会话标题" placeholder="新会话名称" value={newTitle} disabled={creating||!!activeRun} onChange={e=>setNewTitle(e.target.value)}/><button aria-label="新建原生会话" disabled={!newTitle.trim()||creating||!!activeRun} title="使用当前 Harness 原生预设创建，不强制指定模型" onClick={()=>void protect(async()=>{setCreating(true);try{const created=await api<Conversation>('/api/sessions',{harness:newHarness,title:newTitle.trim()});setSessions(old=>[created,...old.filter(c=>key(c)!==key(created))]);setNewTitle('');add(created);setNotice('原生会话已创建，模型沿用 Harness 预设。');}finally{setCreating(false);}})}>{creating?<LoaderCircle className="spin" size={15}/>:<Plus size={15}/>}</button></div>
        <div className="sidebar-foot"><Terminal size={14}/><span>当前 Linux 服务器 · 原生会话</span></div></aside>
      {panels.separator('left')}
      <section className="center-panel"><div className="canvas-toolbar"><div><span className="eyebrow">02 / ORCHESTRATION</span><input className="workflow-name" aria-label="流程名称" disabled={!!activeRun} value={workflow.name} onChange={e=>setWorkflow(w=>({...w,name:e.target.value}))}/></div><div className="toolbar-actions"><button disabled={!!activeRun} onClick={()=>void loop()} title="将已勾选的两个会话生成三步接力">A → B → A</button><button className="pixel-toggle" aria-label="像素员工" aria-pressed={pixels.enabled} title={pixels.reduced?'像素员工 · 系统已启用减少动态效果':'像素员工与工位，可关闭并记忆设置'} onClick={pixels.toggle}><span aria-hidden="true">▦</span><span>员工</span></button><button onClick={save} disabled={!workflow.nodes.length}>保存</button>{activeRun?<button className="run-button" onClick={()=>void protect(async()=>{await api(`/api/runs/${activeRun.id}/pause`,{paused:activeRun.state!=='paused'});})}>{activeRun.state==='paused'?<Play size={15}/>:<Pause size={15}/>} {activeRun.state==='paused'?'继续':'暂停后续'}</button>:<button className="run-button" disabled={!workflow.nodes.length||starting} onClick={start}>{starting?<LoaderCircle className="spin" size={15}/>:<Play size={15}/>}运行</button>}</div></div>
        <div className="canvas" onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';}} onDrop={e=>{e.preventDefault();const s=sessions.find(c=>key(c)===e.dataTransfer.getData('application/sessionweave'));if(s)add(s,flow.screenToFlowPosition({x:e.clientX,y:e.clientY}));}}>
          <ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={changes} onConnect={connect} onNodeClick={(_e,n)=>{setSelected(n.id);setShowRun(false);}} onPaneClick={()=>setSelected(undefined)} nodesDraggable={!activeRun} nodesConnectable={!activeRun} deleteKeyCode={null} fitView minZoom={.35} maxZoom={1.6}><Background color="var(--canvas-dot)" gap={22} size={1}/><Controls showInteractive={false}/>{ready&&pixels.enabled&&workflow.nodes.length>0&&<EmployeeLayer key={workflow.id} workflow={workflow} run={run} sessions={sessions} dimensions={dimensions} motion={pixels.motion} onSelect={id=>{setSelected(id);setShowRun(false);}}/>}</ReactFlow>
          {!workflow.nodes.length&&<div className="canvas-empty"><div className="empty-glyph"><GitBranch size={38}/></div><span className="eyebrow">FROM CONVERSATIONS TO COLLABORATION</span><h1>把思路，编织成流程。</h1><p>将左侧会话拖进来，连接它们。<br/>或者在右侧描述你想完成的协作。</p><div className="example-route"><span>研究 A</span><ArrowRight size={16}/><span>评审 B</span><ArrowRight size={16}/><span>修订 A</span></div><small>每个节点是一步任务，同一会话可以多次参与。</small></div>}
          {!!workflow.nodes.length&&<div className="canvas-caption">{workflow.nodes.length} STEPS <span>·</span> {workflow.edges.length} CONNECTIONS <span>·</span> {pixels.enabled?`${new Set(workflow.nodes.map(n=>key(n.conversationRef))).size} 员工 · 真实会话接力`:'真实会话接力'}</div>}
        </div>
        {(step||showRun)&&<div className="detail-panel"><div className="detail-head"><div className="detail-tabs"><button className={!showRun?'active':''} onClick={()=>setShowRun(false)} disabled={!step}>步骤设置</button><button className={showRun?'active':''} onClick={()=>setShowRun(true)}>运行记录 {run&&<span className={run.state}>{labels[run.state]}</span>}</button></div><div className="detail-actions">{step&&!showRun&&<button disabled={!!activeRun} className="icon-button" aria-label="删除步骤" onClick={remove}><Trash2 size={15}/></button>}<button className="icon-button" aria-label="关闭详情" onClick={()=>{setSelected(undefined);setShowRun(false);}}><X size={16}/></button></div></div>
          {showRun?<div className="run-detail">{run?<><select aria-label="运行历史" value={run.id} onChange={e=>setRunId(e.target.value)}>{runs.map(r=><option value={r.id} key={r.id}>{new Date(r.createdAt).toLocaleString()} · {r.workflow.name} · {labels[r.state]}</option>)}</select><div className="run-nodes">{run.nodes.map(n=><details key={n.id} open={n.nodeId===selected}><summary><span className={`status-dot ${n.state}`}/><strong>{n.nodeId}</strong>{labels[n.state]}<small>{n.activity}</small></summary>{n.error&&<p className="inline-error">{n.error}</p>}<div className="snapshot-meta">{n.nativeTurnOrMessageId} {n.model&&` · ${n.model} · ${n.effort||'Default'}`}</div>{n.actualSentPrompt&&<details><summary>实际发送的提示词</summary><pre>{n.actualSentPrompt}</pre></details>}<h4>最终输出快照</h4><pre>{n.outputSnapshot||'等待本轮完成后固定输出。'}</pre></details>)}</div></>:<div className="empty-list">运行后这里会显示实际输入与输出快照</div>}</div>:step&&<div className="step-editor"><div className="editor-main"><div className="step-settings"><input aria-label="步骤用途" value={step.purpose} disabled={!!activeRun} onChange={e=>patchStep({purpose:e.target.value})}/><select aria-label="执行模式" disabled={!!activeRun} value={step.mode} onChange={e=>patchStep({mode:e.target.value as Step['mode'],...(e.target.value==='listen'?{selectedSkills:[],selectedFiles:[],upstreamOutputRefs:[]}: {})})}><option value="kickoff">发起新一轮任务</option><option value="listen">监听当前在途任务</option></select></div>
            {c&&<ModelPicker key={key(c)} conversation={c} onOpenReady={open=>{modelPickerOpen.current=open;}} disabled={!!activeRun||c.state==='running'} onUpdate={updated=>setSessions(old=>old.map(item=>key(item)===key(updated)?{...item,...updated,preview:item.preview}:item))}/>}
            {step.mode==='kickoff'?<Composer identity={key(step.conversationRef)} harness={step.conversationRef.harness} value={step.promptTemplate} onChange={text=>patchStep({promptTemplate:text})} historyTexts={historyTexts} skills={resources[key(step.conversationRef)]?.skills||[]} upstream={upstream} onModel={()=>modelPickerOpen.current?.()} onSkill={id=>patchStep({selectedSkills:[...new Set([...step.selectedSkills,id])]})} disabled={!!activeRun}/>:<div className="listen-explanation"><Clock3 size={22}/><p>绑定原客户端正在执行的当前轮次。不会发送这一步的提示词，完成后保存回答并接力。</p></div>}
            <div className="editor-hint"><span>↑ ↓ 历史 · $ / @ Skill · /model 模型{step.conversationRef.harness==='opencode'?' · /skill':''}</span><span>{step.promptTemplate.length} 字符</span></div><small className="composer-scope">网页任务编辑器：原生管理命令和 ! Shell 请在 CLI / TUI 中执行。</small>{nodeRun?.error&&<p className="inline-error">{nodeRun.error}</p>}</div>
            <div className="editor-resources"><label className="eyebrow">CONTEXT & RESOURCES</label>{step.mode==='kickoff'&&<><div className="resource-heading">上游输出</div>{upstream.length?upstream.map(id=><label className="check-row" key={id}><input type="checkbox" disabled={!!activeRun} checked={step.upstreamOutputRefs.includes(id)} onChange={e=>patchStep({upstreamOutputRefs:e.target.checked?[...step.upstreamOutputRefs,id]:step.upstreamOutputRefs.filter(r=>r!==id)})}/>{id}.output</label>):<small className="muted">连接上游节点后可引用输出</small>}<label className="check-row"><input type="checkbox" disabled={!!activeRun} checked={step.polishBeforeSend} onChange={e=>patchStep({polishBeforeSend:e.target.checked})}/>接力前润色指令</label><div className="resource-heading">Skill</div>{(resources[key(step.conversationRef)]?.skills||[]).map(s=><label className="check-row" title={s.description} key={s.id}><input type="checkbox" disabled={!!activeRun} checked={step.selectedSkills.includes(s.id)} onChange={e=>patchStep({selectedSkills:e.target.checked?[...step.selectedSkills,s.id]:step.selectedSkills.filter(id=>id!==s.id)})}/>{s.name}</label>)}<div className="resource-heading">文件引用</div><div className="file-search"><input disabled={!!activeRun} aria-label="搜索文件" placeholder="输入文件名" value={fileQuery} onChange={e=>setFileQuery(e.target.value)}/><button disabled={!!activeRun} onClick={findFiles}><Search size={13}/></button></div>{fileResults.slice(0,6).map(f=><button disabled={!!activeRun} className="file-result" key={f} onClick={()=>patchStep({selectedFiles:[...new Set([...step.selectedFiles,f.startsWith('/')?f:`${c?.cwd}/${f}`])]})}><FileText size={12}/>{f}</button>)}{step.selectedFiles.map(f=><button disabled={!!activeRun} className="file-result selected-file" key={f} onClick={()=>patchStep({selectedFiles:step.selectedFiles.filter(x=>x!==f)})}>{f.split('/').pop()} <X size={12}/></button>)}</>}</div>
          </div>}
        </div>}
        <div className="canvas-bottom"><span><span className={`status-dot ${activeRun?'running':''}`}/>{activeRun?activeRun.state==='paused'?'后续派发已暂停，在途任务继续':'后端持续运行，关闭网页不影响接力':'就绪 · 点击运行才发送任务'}</span><button onClick={()=>setShowRun(!showRun)}><Clock3 size={13}/>运行记录 {runs.length>0&&`(${runs.length})`}</button></div>
      </section>
      {panels.separator('right')}
      <aside className={`plan-panel ${mobilePanel==='plan'?'mobile-open':''}`}><div className="panel-title"><div><span className="eyebrow">03 / INTENT TO FLOW</span><h2><Sparkles size={18}/>从想法开始</h2></div><span className="ai-badge">AI</span></div><p className="plan-intro">描述你想让会话怎样协作。<br/>先看文字方案，确认后再生成画布。</p>
        <div className="model-label"><span className="status-dot connected"/>Space Bunny <span>{chosen.length&&chosen.every(k=>sessions.find(c=>key(c)===k)?.testing)?'Low · 测试':'Default'}</span></div><textarea className="natural-input" aria-label="自然语言需求" placeholder="例如：让 OpenCode 的 A 调研这个主题，再由 Codex 的 B 提出批判意见，最后回到 A 修订并结束。" value={description} onChange={e=>setDescription(e.target.value)}/>
        <div className="resource-heading">参与的会话 <span>{chosen.length}</span></div><div className="chosen-sessions">{chosen.length?chosen.map(k=>{const s=sessions.find(c=>key(c)===k);return s&&<div className="chosen-session" key={k}><div><span className={`harness ${s.harness}`}>{s.harness==='codex'?'CX':'OC'}</span><strong>{s.title}</strong><button className="icon-button" aria-label={`移除 ${s.title}`} onClick={()=>setChosen(old=>old.filter(x=>x!==k))}><X size={12}/></button></div>{resources[k]?.skills.map(skill=><label className="check-row" key={skill.id}><input type="checkbox" checked={(planSkills[k]||[]).includes(skill.id)} onChange={e=>setPlanSkills(old=>({...old,[k]:e.target.checked?[...(old[k]||[]),skill.id]:(old[k]||[]).filter(id=>id!==skill.id)}))}/>{skill.name}</label>)}</div>;}):<div className="choose-hint"><Layers3 size={17}/>在左侧勾选真实会话<br/>Skill 也可以在这里选择</div>}</div>
        <button className="generate-button" disabled={!description.trim()||!chosen.length||planning||!!activeRun} onClick={generate}>{planning?<LoaderCircle size={16} className="spin"/>:<Sparkles size={16}/>} {planning?'正在整理协作步骤…':draft?'按描述修改草稿':'生成文字方案'}<ChevronRight size={15}/></button>
        {draft&&<div className="draft-plan"><div className="draft-title"><span className="eyebrow">PLAN DRAFT</span><span>{draft.nodes.length} 步</span></div><input aria-label="草稿名称" value={draft.name} onChange={e=>setDraft(d=>d&&({...d,name:e.target.value}))}/>{draft.nodes.map((n,i)=><div className="draft-step" key={n.id}><span className="draft-number">{i+1}</span><div><input aria-label={`草稿 ${n.id} 用途`} value={n.purpose} onChange={e=>setDraft(d=>d&&({...d,nodes:d.nodes.map(x=>x.id===n.id?{...x,purpose:e.target.value}:x)}))}/><small>{sessions.find(c=>key(c)===key(n.conversationRef))?.title} · {n.mode==='listen'?'监听':'发送任务'}</small><textarea aria-label={`草稿 ${n.id} 提示词`} value={n.promptTemplate} onChange={e=>setDraft(d=>d&&({...d,nodes:d.nodes.map(x=>x.id===n.id?{...x,promptTemplate:e.target.value}:x)}))}/>{n.upstreamOutputRefs.length>0&&<span className="draft-reference">读取 {n.upstreamOutputRefs.join(', ')} 的输出，润色后接力</span>}</div></div>)}<button className="confirm-button" disabled={!!activeRun} onClick={confirm}><CheckCircle2 size={16}/>确认方案，生成画布</button><small className="confirm-note">确认仅更新画布，不会发送消息。</small></div>}
        {!draft&&<div className="plan-path"><span>01 描述协作</span><ArrowRight size={12}/><span>02 确认步骤</span><ArrowRight size={12}/><span>03 运行画布</span></div>}<div className="plan-foot"><GitBranch size={14}/><span>规划与润色使用独立辅助会话</span></div>
      </aside>
    </main>
  </div>;
}
export default function App(){return <ReactFlowProvider><Workbench/></ReactFlowProvider>;}
